print('Ola mundo!!')
nome = input('digite seu nome:')
print('É um prazer te conhecer', nome)
m1 = int(input( 'digite um numero:' ))
m2 = int(input('digite um numero:'))
s1 = (m1+m2)
print('a soma de {} e do numero {} é igual a: {}'.format(m1, m2, s1))
